source 'https://rubygems.org'
gem 'rake'
gem "daemons"
gem "sinatra"
gem "sequel"
gem "mysql2"
gem "thin"
gem "haml"
gem "rspec"
gem "rack-test"
gem "i18n"
gem 'bibtex-ruby'
gem 'levenshtein-ffi', :require => 'levenshtein'
gem 'serrano'
gem 'dotenv'
gem 'scopus'
gem 'nokogiri'
gem 'moneta'
gem 'nbayes'
gem 'ruby-stemmer'
gem 'classifier-reborn'
gem 'categorize'
gem 'ai4r'
gem 'pdf-reader'