version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-sinatra
    docker:
      - image: cimg/ruby:2.7.5-browsers
        environment:
          TESTOPTS: "--ci-dir=/tmp/test-results"
          APP_ENV: test
    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
          # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter      
      # Restore bundle cache
      - type: cache-restore
        key: sinatra-demo-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: sinatra-demo-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run:
          name: Pre test
          command: |
            ./cc-test-reporter before-build

      # Run minitest
      - type: shell
        command: bundle exec rake
      - run:
          name: Post test
          command: |
            ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
