version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-sinatra
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          TESTOPTS: "--ci-dir=/tmp/test-results"
          APP_ENV: test
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: sinatra-demo-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: sinatra-demo-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Run minitest
      - type: shell
        command: bundle exec rake

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
